---
# This file extracts a secret from the config file. If it is not found, a new value is generated.
# In either case, the secret is made available in a variable for future reference.
# Needs:
# * _slurp_appini - base64-encoded contents of app.ini
# * secret - the name of the secret to handle

- name: "Extract {{ secret }} from current config file"
  ansible.builtin.set_fact:
    _secret_value: "{{ _slurp_appini.content | ansible.builtin.b64decode | ansible.builtin.regex_search('(?<=' ~ secret ~ '\\s=\\s`).*(?=`)') }}"
  no_log: true
  when: "_slurp_appini is not skipped"

- name: "Generate new {{ secret }}"
  ansible.builtin.command: "gitea generate secret {{ secret | ansible.builtin.quote }}"
  environment:
    PATH: "{{ ansible_facts['env']['PATH'] }}:/usr/local/bin"
  register: _generate_secret
  no_log: true
  when: "not _secret_value | default(false)"

- name: "Store new {{ secret }}"
  ansible.builtin.set_fact:
    '_{{ secret }}': "{{ _generate_secret.stdout | default(_secret_value) }}"
  no_log: true
